version: '2'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - '25565:25565/udp'
    volumes:
      - './minecraft/minecraft-data:/data'
    restart: always
    labels:
      - 'traefik.enable=false'
    environment:
      - 'EULA=TRUE'
